name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Install Jest
      run: npm install --save-dev jest

    - name: Проверка установки Jest
      run: ls -l node_modules/.bin/jest

    - name: Fix Jest permissions
      run: chmod +x node_modules/.bin/jest

    - name: Check Jest version
      run: npx jest --version

    - name: Run tests
      run: npm test
